mapping = {
            # Primeros puestos
            "PRIMEROS PUESTOS DE I. E. DE NIVEL SECUNDARIO": "1ER Y 2DO PUESTO DE INSTITUCIONES E.",
            "PRIMEROS PUESTOS DE LAS I. E. DE NIVEL SECUNDARIO": "1ER Y 2DO PUESTO DE INSTITUCIONES E.",
            "1ER Y 2DO PUESTO DE I.E.": "1ER Y 2DO PUESTO DE INSTITUCIONES E.",
            "1ER Y 2DO PUESTO I.E.": "1ER Y 2DO PUESTO DE INSTITUCIONES E.",
            "PRIMEROS PUESTOS COLEGIOS": "1ER Y 2DO PUESTO DE INSTITUCIONES E.",
            "PRIMEROS PUESTOS DE EDUCACIÓN SECUNDARIA": "1ER Y 2DO PUESTO DE INSTITUCIONES E.",

            # Víctimas de terrorismo
            "VICTIMAS DEL TERRORISMO": "VICTIMA DE TERRORISMO",
            "VICTIMA DEL TERRORISMO": "VICTIMA DE TERRORISMO",
            "VICTIMAS DE TERRORISMO": "VICTIMA DE TERRORISMO",

            # Deportistas
            "DEPORTISTAS CALIFICADOS": "DEPORTISTAS DESTACADOS",
            "DEP. CALIFICADOS Y DEP. CALIFICADOS DE ALTO NIVEL": "DEPORTISTAS DESTACADOS",
            "DEP. CALIFICADOS Y/O DEP. CALIFICADOS DE ALTO NIVEL": "DEPORTISTAS DESTACADOS",
            "DEPORTISTAS DESTACADOS": "DEPORTISTAS DESTACADOS",
            "DEPORTISTAS DESCATADOS": "DEPORTISTAS DESTACADOS",

            # Discapacidad
            "PERSONA CON DISCAPACIDAD": "PERSONA CON DISCAPACIDAD",
            "PERSONAS CON DISCAPACIDAD": "PERSONA CON DISCAPACIDAD",

            # Ordinaria
            "ADMISIÓN ORDINARIA": "ORDINARIA",
            "ORDINARIA": "ORDINARIA",
            "ORDINARIO": "ORDINARIA",
            "EDUCACIÓN BÁSICA REGULAR Y EDUCACIÓN BÁSICA ALTERNATIVA": "ORDINARIA",

            # Otros
            "SERVIDORES DE LA UNICA E HIJOS": "SERVIDORES DE LA UNICA E HIJOS",
            "TITULADOS Y GRADUADOS": "TITULADOS O GRADUADOS",
            "TITULADOS O GRADUADOS": "TITULADOS O GRADUADOS",
            "COLEGIO SECUNDARIO MAYOR PRESIDENTE DEL PERU": "COLEGIO SECUNDARIO MAYOR PRESIDENTE DEL PERU",
            "COMUNIDADES RURALES Y URBANAS": "COMUNIDADES RURALES Y URBANAS",

            # 2016
            "ORDINARIOS" : "ORDINARIA",
            "PRIMEROS PUESTOS" : "1ER Y 2DO PUESTO DE INSTITUCIONES E.",
            "DISCAPACITADOS" : "PERSONA CON DISCAPACIDAD",
            "HIJOS DE SERVIDOR"  : "SERVIDORES DE LA UNICA E HIJOS",
            "DEPOR. CALIFICADOS" : "DEPORTISTAS DESTACADOS",
            "TRASLADOS INTERNOS" : "TRASLADOS INTERNOS",
            "TRASLADOS EXTERNOS" : "TRASLADOS EXTERNOS",
            "COLEGIO PRESIDENTE" : "COLEGIO SECUNDARIO MAYOR PRESIDENTE DEL PERU",

            #2017
            "VICTIMAS DEL TERRORISMO - LEY 27277" : "VICTIMA DE TERRORISMO",
            "DISCAPACITADOS - LEY Nº 27050" : "PERSONA CON DISCAPACIDAD",
            "COLEGIO PRESIDENTE DE LA REPUBLICA" : "COLEGIO SECUNDARIO MAYOR PRESIDENTE DEL PERU",
            "DEPORTISTAS CALIFICADOS DE ALTO NIVEL" : "DEPORTISTAS DESTACADOS",
            "EXONERADOS COLEGIOS" : "1ER Y 2DO PUESTO DE INSTITUCIONES E.", #(Por revisar)
            "POSTULANTES ORDINARIOS" : "ORDINARIA"



        }

dict_carreras = {
    "ADMINISTRACION": "ADMINISTRACIÓN",
    "AGRONOMIA": "AGRONOMÍA",
    "ARQUEOLOGIA": "ARQUEOLOGÍA",
    "BIOLOGIA": "BIOLOGÍA",
    "CIENCIAS DE LA COMUNICACION": "CIENCIAS DE LA COMUNICACIÓN",
    "ECONOMIA": "ECONOMÍA",
    "ENFERMERIA": "ENFERMERÍA",
    "ESTADISTICA": "ESTADÍSTICA",
    "FARMACIA Y BIOQUIMICA": "FARMACIA Y BIOQUÍMICA",
    "FISICA": "FÍSICA",
    "HISTORIA, GEOGRAFÍA": "CIENCIAS DE LA EDUCACIÓN EN HISTORIA Y GEOGRAFÍA",
    "HISTORIA Y GEOGRAFÍA": "CIENCIAS DE LA EDUCACIÓN EN HISTORIA Y GEOGRAFÍA",
    "CIENCIAS BIOLÓGICAS": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS BIOLÓGICAS Y QUÍMICA": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS DE LA EDUCACION EN CIENCIAS BIOLOGICAS Y": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS DE LA EDUCACION EN CIENCIAS BIOLOGICAS Y QUIMICA": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS DE LA EDUCACION EN CIENCIAS BIOLÓGICAS Y QUÍMI": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS DE LA EDUCACION EN EDUCACION ARTISTICA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTÍSTICA",
    "CIENCIAS DE LA EDUCACION EN EDUCACION FISICA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN FÍSICA",
    "CIENCIAS DE LA EDUCACION EN EDUCACION INICIAL": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN INICIAL",
    "CIENCIAS DE LA EDUCACION EN EDUCACION PRIMARIA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN PRIMARIA",
    "CIENCIAS DE LA EDUCACION EN FILOSOFIA": "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES",
    "CIENCIAS DE LA EDUCACION EN HISTORIA Y GEOGRAFIA": "CIENCIAS DE LA EDUCACIÓN EN HISTORIA Y GEOGRAFÍA",
    "CIENCIAS DE LA EDUCACION EN LENGUA Y LITERATURA": "CIENCIAS DE LA EDUCACIÓN EN LENGUA Y LITERATURA",
    "CIENCIAS DE LA EDUCACION EN MATEMATICA E INFORMATICA": "CIENCIAS DE LA EDUCACIÓN EN MATEMÁTICA E INFORMÁTICA",
    "CIENCIAS DE LA EDUCACION EN CIENCIAS BIOLOGICAS Y": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS DE LA EDUCACION EN CIENCIAS BIOLOGICAS Y QUIMICA": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "CIENCIAS DE LA EDUCACION EN EDUCACION ARTISTICA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTÍSTICA",
    "CIENCIAS DE LA EDUCACION EN FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES": "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES",
    "FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES": "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES",
    "EDUCACIÓN INICIAL": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN INICIAL",
    "EDUCACIÓN PRIMARIA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN PRIMARIA",
    "EDUCACIÓN ARTÍSTICA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTÍSTICA",
    "CIENCIAS MATEMÁTICAS E INFORMÁTICA": "CIENCIAS DE LA EDUCACIÓN EN MATEMÁTICA E INFORMÁTICA",
    "MATEMATICA E INFORMATICA": "CIENCIAS DE LA EDUCACIÓN EN MATEMÁTICA E INFORMÁTICA",
    "LENGUA Y LITERATURA": "CIENCIAS DE LA EDUCACIÓN EN LENGUA Y LITERATURA",
    "INGENIERIA AMBIENTAL Y SANITARIA": "INGENIERÍA AMBIENTAL Y SANITARIA",
    "INGENIERIA CIVIL": "INGENIERÍA CIVIL",
    "INGENIERIA DE ALIMENTOS": "INGENIERÍA DE ALIMENTOS",
    "INGENIERIA DE MINAS": "INGENIERÍA DE MINAS",
    "INGENIERIA DE SISTEMAS": "INGENIERÍA DE SISTEMAS",
    "INGENIERIA ELECTRONICA": "INGENIERÍA ELECTRÓNICA",
    "INGENIERIA MECANICA Y ELECTRICA": "INGENIERÍA MECÁNICA ELÉCTRICA",
    "INGENIERIA MECANICA Y ELÉCTRICA": "INGENIERÍA MECÁNICA ELÉCTRICA",
    "INGENIERIA METALURGICA": "INGENIERÍA METALÚRGICA",
    "INGENIERIA PESQUERA": "INGENIERÍA PESQUERA",
    "INGENIERIA QUIMICA": "INGENIERÍA QUÍMICA",
    "MEDICINA VETERINARIA Y ZOOTÉCNICA": "MEDICINA VETERINARIA Y ZOOTECNIA",
    "ODONTOLOGIA": "ODONTOLOGÍA",
    "PSICOLOGIA": "PSICOLOGÍA",
    "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIE": "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES",
    "INGENIERÍA MECÁNICA Y ELÉCTRICA": "INGENIERÍA MECÁNICA ELÉCTRICA",
    "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMI": "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA",
    "EDUCACIÓN FÍSICA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN FÍSICA",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTISTICA": "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTÍSTICA"
}

dict_facultades = {
    # Ciencias de la Educación y Humanidades
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTÍSTICA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN FÍSICA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN INICIAL": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN PRIMARIA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN HISTORIA Y GEOGRAFÍA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN LENGUA Y LITERATURA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    "CIENCIAS DE LA EDUCACIÓN EN MATEMÁTICA E INFORMÁTICA": "CIENCIAS DE LA EDUCACIÓN Y HUMANIDADES",
    
    # Ciencias
    "MATEMÁTICA E INFORMÁTICA": "CIENCIAS",
    "ESTADÍSTICA": "CIENCIAS",
    "FÍSICA": "CIENCIAS",
    
    # Ciencias Económicas y Negocios
    "ECONOMÍA": "CIENCIAS ECONÓMICAS Y NEGOCIOS INTERNACIONALES",
    "NEGOCIOS INTERNACIONALES": "CIENCIAS ECONÓMICAS Y NEGOCIOS INTERNACIONALES",
    
    # Administración y Contabilidad
    "ADMINISTRACIÓN": "ADMINISTRACIÓN",
    "AGRONOMÍA": "AGRONOMÍA",
    "CONTABILIDAD": "CONTABILIDAD",
    
    # Derecho
    "DERECHO": "DERECHO Y CIENCIA POLÍTICA",
    
    # Ciencias de la Comunicación, Turismo y Arqueología
    "CIENCIAS DE LA COMUNICACIÓN": "CIENCIAS DE LA COMUNICACIÓN, TURISMO Y ARQUEOLOGÍA",
    "TURISMO": "CIENCIAS DE LA COMUNICACIÓN, TURISMO Y ARQUEOLOGÍA",
    "ARQUEOLOGÍA": "CIENCIAS DE LA COMUNICACIÓN, TURISMO Y ARQUEOLOGÍA",
    
    # Ingeniería
    "INGENIERÍA AMBIENTAL Y SANITARIA": "INGENIERÍA AMBIENTAL Y SANITARIA",
    "INGENIERÍA CIVIL": "INGENIERÍA CIVIL",
    "INGENIERÍA DE MINAS": "INGENIERÍA DE MINAS Y METALURGIA",
    "INGENIERÍA METALÚRGICA": "INGENIERÍA DE MINAS Y METALURGIA",
    "INGENIERÍA DE SISTEMAS": "INGENIERÍA DE SISTEMAS",
    "INGENIERÍA ELECTRÓNICA": "INGENIERÍA MECÁNICA Y ELÉCTRICA",
    "INGENIERÍA MECÁNICA ELÉCTRICA": "INGENIERÍA MECÁNICA Y ELÉCTRICA",
    "INGENIERÍA DE ALIMENTOS": "INGENIERÍA PESQUERA Y DE ALIMENTOS",
    "INGENIERÍA PESQUERA": "INGENIERÍA PESQUERA Y DE ALIMENTOS",
    "INGENIERÍA QUÍMICA": "INGENIERÍA QUÍMICA Y PETROQUÍMICA",
    
    # Ciencias Biológicas y Medicina
    "BIOLOGÍA": "CIENCIAS BIOLÓGICAS",
    "ENFERMERÍA": "ENFERMERÍA",
    "MEDICINA HUMANA": "MEDICINA HUMANA",
    "MEDICINA VETERINARIA Y ZOOTECNIA": "MEDICINA VETERINARIA Y ZOOTECNIA",
    "OBSTETRICIA": "OBSTETRICIA",
    "ODONTOLOGÍA": "ODONTOLOGÍA",
    "PSICOLOGÍA": "PSICOLOGÍA",
    "FARMACIA Y BIOQUÍMICA": "FARMACIA Y BIOQUÍMICA",
    
    # Otras
    "ARQUITECTURA": "ARQUITECTURA"
}

dict_area = {
    # Área A: Ciencias de la Salud
    "FARMACIA Y BIOQUÍMICA": "A",
    "OBSTETRICIA": "A",
    "ODONTOLOGÍA": "A",
    "ENFERMERÍA": "A",
    "MEDICINA VETERINARIA Y ZOOTECNIA": "A",
    "MEDICINA HUMANA": "A",
    "PSICOLOGÍA": "A",
    "BIOLOGÍA": "A",

    # Área B: Ciencias Sociales y Humanidades
    "ARQUEOLOGÍA": "B",
    "CONTABILIDAD": "B",
    "CIENCIAS DE LA EDUCACIÓN EN CIENCIAS BIOLÓGICAS Y QUÍMICA": "B",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN PRIMARIA": "B",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN FÍSICA": "B",
    "DERECHO": "B",
    "CIENCIAS DE LA EDUCACIÓN EN MATEMÁTICA E INFORMÁTICA": "B",
    "ADMINISTRACIÓN": "B",
    "ECONOMÍA": "B",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN ARTÍSTICA": "B",
    "CIENCIAS DE LA EDUCACIÓN EN EDUCACIÓN INICIAL": "B",
    "CIENCIAS DE LA EDUCACIÓN EN HISTORIA Y GEOGRAFÍA": "B",
    "TURISMO": "B",
    "CIENCIAS DE LA COMUNICACIÓN": "B",
    "NEGOCIOS INTERNACIONALES": "B",
    "CIENCIAS DE LA EDUCACIÓN EN LENGUA Y LITERATURA": "B",
    "CIENCIAS DE LA EDUCACIÓN EN FILOSOFÍA, PSICOLOGÍA Y CIENCIAS SOCIALES": "B",

    # Área C: Ciencias e Ingeniería
    "INGENIERÍA DE ALIMENTOS": "C",
    "INGENIERÍA DE SISTEMAS": "C",
    "INGENIERÍA AMBIENTAL Y SANITARIA": "C",
    "INGENIERÍA PESQUERA": "C",
    "INGENIERÍA DE MINAS": "C",
    "INGENIERÍA METALÚRGICA": "C",
    "INGENIERÍA CIVIL": "C",
    "INGENIERÍA ELECTRÓNICA": "C",
    "ESTADÍSTICA": "C",
    "INGENIERÍA QUÍMICA": "C",
    "ARQUITECTURA": "C",
    "INGENIERÍA MECÁNICA ELÉCTRICA": "C",
    "FÍSICA": "C",
    "MATEMÁTICA E INFORMÁTICA": "C",
    "AGRONOMÍA": "C"
}

